export const products = [
  {
    id: 1,
    artist: "Mendigando",
    album: "Mundo nuevo",
    year: 2020,
    price: 5,
    category: "rock",
    image: "/img/2020MendigandoMundoNuevo.jpg",
  },
  {
    id: 2,
    artist: "Mendigando",
    album: "Salvaje",
    year: 2017,
    price: 6,
    category: "rock",
    image: "/img/2017MendigandoSalvaje.jpg",
  },
  {
    id: 3,
    artist: "Nine Lives",
    album: "Hablar al pedo",
    year: 2017,
    price: 8,
    category: "punk",
    image: "/img/2008NineLivesHablarAlPedo.jpg",
  },
  {
    id: 4,
    artist: "Da Skate",
    album: "Diecisiete",
    year: 2017,
    price: 10,
    category: "punk",
    image: "/img/2017DaSkateDiecisiete.jpg",
  },
  {
    id: 5,
    artist: "Loli Molina",
    album: "Lo azul sobre mi",
    year: 2019,
    price: 10,
    category: "cantautor",
    image: "/img/2019LoliMolinaLoAzulSobreMi.jpg",
  },
  {
    id: 6,
    artist: "Científicos del palo",
    album: "La histeria Argentina",
    year: 2013,
    price: 9,
    category: "rock",
    image: "/img/2013CientificosDelPaloLaHisteriaArgentina.jpg",
  },
  {
    id: 7,
    artist: "Aladelta",
    album: "Teleficción",
    year: 2011,
    price: 6,
    category: "rock",
    image: "/img/2011AladeltaTeleficcion.jpg",
  },
  {
    id: 8,
    artist: "Aladelta",
    album: "Descubre",
    year: 2008,
    price: 7,
    category: "rock",
    image: "/img/2008AladeltaDescubre.jpg",
  },
  {
    id: 9,
    artist: "Bárbara Gilles",
    album: "Tesina",
    year: 2020,
    price: 5,
    category: "cantautor",
    image: "/img/2020BarbaraGillesTesina.jpg",
  },
  {
    id: 10,
    artist: "León Rogani",
    album: "La invención de la noche",
    year: 2013,
    price: 4,
    category: "cantautor",
    image: "/img/2013LeonRoganiLaInvencionDeLaNoche.jpg",
  },
  {
    id: 11,
    artist: "Galo",
    album: "Rizoma",
    year: 2021,
    price: 5,
    category: "cantautor",
    image: "/img/2021GaloRizoma.jpg",
  },
  {
    id: 12,
    artist: "Condor",
    album: "Condor",
    year: 2018,
    price: 6,
    category: "cantautor",
    image: "/img/2018CondorCondor.jpg",
  },
  {
    id: 13,
    artist: "Boom Boom Kid",
    album: "Bien-venido: Zona de Descan-zo",
    year: 2020,
    price: 12,
    category: "rock",
    image: "/img/2020BoomBoomKidBienvenidoZonaDeDescanzo.jpg",
  },
  {
    id: 14,
    artist: "Fun People",
    album: "Anesthesia",
    year: 1995,
    price: 15,
    category: "rock",
    image: "/img/1995FunPeopleAnesthesia.jpg",
  },
  {
    id: 15,
    artist: "Lucia Boffo",
    album: "Nomade",
    year: 2022,
    price: 10,
    category: "cantautor",
    image: "/img/2022LuciaBoffoNomade.jpg",
  },
  {
    id: 16,
    artist: "Bandera de niebla",
    album: "Desindustral",
    year: 2014,
    price: 8,
    category: "rock",
    image: "/img/2014BanderaDeNieblaDesindustral.jpg",
  },
];
